services:
  backend:
      build:
        context: ./codenames-backend
      container_name: codenames-backend
      ports:
        - "8080:8080"
      environment:
        - SPRING_PROFILES_ACTIVE=dev
        - SECRET=${SECRET}
        - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
        - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
        - MONGO_URI=${MONGO_URI}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      volumes:
        - ./codenames-backend:/opt/codenames-backend
      networks:
        - codenames-network

  frontend:
    build:
      context: ./codenames-frontend
    container_name: codenames-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./codenames-frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - backend
    networks:
        - codenames-network
        
networks:
    codenames-network:
        driver: bridge