spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 20196963430-88kq84ti603tipgeg6kvu5fhr5q9fsum.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
