name: 🚀 Deploy on Google Cloud Run

on:
  push:
    branches: [main]

env:
  BACKEND_ENV_YAML: ${{ secrets.BACKEND_ENV_YAML }}
  
jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/35261654330/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-deployer@codenames-458106.iam.gserviceaccount.com'

    - name: 'Set up gcloud'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Create env.yaml'
      run: echo "$BACKEND_ENV_YAML" > env.yaml

    - name: 'Deploy codenames-backend'
      run: |
        gcloud builds submit ./codenames-backend --tag gcr.io/codenames-458106/codenames-backend
        gcloud run deploy codenames-backend \
          --image gcr.io/codenames-458106/codenames-backend \
          --region europe-central2 \
          --platform managed \
          --allow-unauthenticated \
          --env-vars-file env.yaml

    - name: 'Remove env.yaml'
      run: rm env.yaml

    - name: 'Deploy codenames-frontend'
      run: |
        gcloud builds submit ./codenames-frontend --tag gcr.io/codenames-458106/codenames-frontend --file ./codenames-frontend/Dockerfile.prod
        gcloud run deploy codenames-frontend \
          --image gcr.io/codenames-458106/codenames-frontend \
          --region europe-central2 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="VITE_BACKEND_API_URL=${{ secrets.VITE_BACKEND_API_URL }},VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}"

    - name: 'Deploy codenames-socket-io-server'
      run: |
        gcloud builds submit ./codenames-socket-io-server --tag gcr.io/codenames-458106/codenames-socket-io-server
        gcloud run deploy codenames-socket-io-server \
          --image gcr.io/codenames-458106/codenames-socket-io-server \
          --region europe-central2 \
          --platform managed \
          --allow-unauthenticated

    - name: 'Deploy codenames-peerserver'
      run: |
        gcloud builds submit ./codenames-peerserver --tag gcr.io/codenames-458106/codenames-peerserver
        gcloud run deploy codenames-peerserver \
          --image gcr.io/codenames-458106/codenames-peerserver \
          --region europe-central2 \
          --platform managed \
          --allow-unauthenticated
