name: Issue Improver Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  improve-issues:
    runs-on: ubuntu-latest

    steps:
    - name: Clarify and Improve Issues with OpenAI GPT
      uses: MaurerKrisztian/issue-improver-action@v1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
