name: 🚀 Push Tag to Main & Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4

      - name: 🔄 Fetch tags
        run: |
          git fetch --tags
          echo "✅ Tagi pobrane"

      - name: 🔍 Get the latest tag on main
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --max-count=1) 2>/dev/null || echo "none")
          echo "Latest tag on main: $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: 📄 Read selected version from file
        run: |
          selected_version=$(cat scripts/selected_version.txt)
          echo "📄 Selected version from file: $selected_version"
          echo "SELECTED_VERSION=$selected_version" >> $GITHUB_ENV

      - name: 🔄 Compare versions and create tag if needed
        run: |
          current_version="${{ env.LATEST_TAG }}"
          selected_version="${{ env.SELECTED_VERSION }}"

          echo "Current version: $current_version"
          echo "Selected version: $selected_version"

          if [ "$selected_version" != "$current_version" ]; then
            echo "🚀 Creating new tag: $selected_version"
            git checkout main
            git tag $selected_version
          else
            echo "⚠️ Selected version is the same as the latest version. No new tag will be created."
            exit 0
          fi

      - name: 🔎 Verify that the tag was created
        run: |
          git tag
          git show-ref --tags | grep ${{ env.SELECTED_VERSION }} || echo "❌ Tag not found!"

      - name: 📤 Push the tag to the remote repository
        run: |
          echo "🚀 Pushing tag: ${{ env.SELECTED_VERSION }}"
          git push origin ${{ env.SELECTED_VERSION }}

  push-docker:
    needs: create-tag
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: 🔍 Fetch and list tags
        run: |
          git fetch --tags 
          git tag        

      - name: 🏷️ Get last tag and set version
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "VERSION=$VERSION" >> $GITHUB_ENV  

      - name: 🔑 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🐳 Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: codenames/codenames-backend:${{ env.VERSION }}
          context: ./codenames-backend  
          file: ./codenames-backend/Dockerfile  

      - name: 🐳 Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: codenames/codenames-frontend:${{ env.VERSION }}
          context: ./codenames-frontend 
          file: ./codenames-frontend/Dockerfile  
