name: Push Tag to Main

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Fetch tags
        run: |
          set -x  # Włączenie debugowania
          git fetch --tags
          echo "✅ Tagi pobrane"

      - name: Get the latest tag on main
        run: |
          set -x  # Włączenie debugowania
          LATEST_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --max-count=1) 2>/dev/null || echo "none")
          echo "🔍 Latest tag on main: $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Read selected version from file
        run: |
          set -x  # Włączenie debugowania
          selected_version=$(cat selected_version.txt)
          echo "📄 Selected version from file: $selected_version"

          echo "SELECTED_VERSION=$selected_version" >> $GITHUB_ENV

      - name: Compare versions and create tag if needed
        run: |
          set -x  # Włączenie debugowania
          current_version="${{ env.LATEST_TAG }}"
          selected_version="${{ env.SELECTED_VERSION }}"

          echo "🔍 Current version: $current_version"
          echo "🔍 Selected version: $selected_version"

          if [ "$selected_version" != "$current_version" ]; then
            echo "🚀 Creating new tag: $selected_version"
            git checkout main
            git tag $selected_version
          else
            echo "⚠️ Selected version is the same as the latest version. No new tag will be created."
            exit 0
          fi

      - name: Verify that the tag was created
        run: |
          set -x  # Włączenie debugowania
          echo "🔎 Checking existing tags..."
          git tag
          echo "🔎 Checking if the new tag exists..."
          git show-ref --tags | grep ${{ env.SELECTED_VERSION }} || echo "❌ Tag not found!"

      - name: Push the tag to the remote repository
        run: |
          set -x  # Włączenie debugowania
          echo "🚀 Pushing tag: ${{ env.SELECTED_VERSION }}"
          git push origin ${{ env.SELECTED_VERSION }}
